name: todo_app
description: "Todo App with Firebase"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.7.0    # compatible avec firebase_core 2.x
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  http: ^0.13.6

  flutter_bloc: any
  equatable: any


  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
